/* DATABASE CREATION SCRIPT */

CREATE DATABASE COURIERTEC_HEREDIA
USE COURIERTEC_HEREDIA

CREATE TABLE CLIENT_TYPE (
	ct_id INT IDENTITY(1,1) PRIMARY KEY,
	ct_name VARCHAR(20) NOT NULL
);

CREATE TABLE PROVINCE (
	p_id INT IDENTITY(1,1) PRIMARY KEY,
	p_name VARCHAR(30) NOT NULL
);

CREATE TABLE CLIENT (
	c_id VARCHAR(30) PRIMARY KEY,
	c_account INT IDENTITY(1,1) NOT NULL UNIQUE,
	c_name VARCHAR(30) NOT NULL,
	c_lname VARCHAR(50) NOT NULL,
	c_telephone VARCHAR(30) NOT NULL,
	c_username VARCHAR(20) NOT NULL UNIQUE,
	c_password VARCHAR(16) NOT NULL,
	c_type INT FOREIGN KEY REFERENCES CLIENT_TYPE(ct_id),
	c_province INT FOREIGN KEY REFERENCES PROVINCE(p_id)
);

CREATE TABLE CATEGORY (
	ca_id INT IDENTITY(1,1) PRIMARY KEY,
	ca_name VARCHAR(30) NOT NULL
);

CREATE TABLE PACKAGE_TYPE (
	pt_id INT IDENTITY(1,1) PRIMARY KEY,
	pt_name VARCHAR(50) NOT NULL,
	pt_price_kg INT NOT NULL,
	pt_category INT FOREIGN KEY REFERENCES CATEGORY(ca_id)
);

CREATE TABLE PACKAGE (
	p_id INT IDENTITY(1,1) PRIMARY KEY,
	p_reception_date DATE NOT NULL,
	p_value INT NOT NULL,
	p_weight INT NOT NULL,
	p_type INT FOREIGN KEY REFERENCES PACKAGE_TYPE(pt_id)
);

CREATE TABLE UBICATION (
	u_id INT IDENTITY(1,1) PRIMARY KEY,
	u_place VARCHAR(50) NOT NULL,
	u_address VARCHAR(100) NOT NULL
);

CREATE TABLE JOB (
	j_id INT IDENTITY(1,1) PRIMARY KEY,
	j_name VARCHAR(50) NOT NULL
);

CREATE TABLE WORKER (
	w_id VARCHAR(30) PRIMARY KEY,
	w_name VARCHAR(30) NOT NULL,
	w_lname VARCHAR(50) NOT NULL,
	w_telephone VARCHAR(30) NOT NULL,
	w_username VARCHAR(20) NOT NULL UNIQUE,
	w_password VARCHAR(16) NOT NULL
);

CREATE TABLE BRANCH_TYPE (
	bt_id INT IDENTITY(1,1) PRIMARY KEY,
	bt_name VARCHAR(30) NOT NULL
);

CREATE TABLE BRANCH (
	b_id INT IDENTITY(1,1) PRIMARY KEY,
	b_telephone VARCHAR(30) NOT NULL,
	b_schedule VARCHAR(30) NOT NULL,
	b_email VARCHAR(100) NOT NULL,
	b_type INT FOREIGN KEY REFERENCES BRANCH_TYPE(bt_id),
	b_ubication INT FOREIGN KEY REFERENCES UBICATION(u_id)
);

CREATE TABLE WORKS_ON (
	wo_branch INT FOREIGN KEY REFERENCES BRANCH(b_id),
	wo_worker VARCHAR(30) FOREIGN KEY REFERENCES WORKER(w_id),
	wo_job INT FOREIGN KEY REFERENCES JOB(j_id)
);

CREATE TABLE PACKAGE_BRANCH (
	pb_id INT IDENTITY(1,1) PRIMARY KEY,
	pb_total INT,
	pb_delivery_date DATE,
	pb_id_package INT FOREIGN KEY REFERENCES PACKAGE(p_id),
	pb_id_client VARCHAR(30) FOREIGN KEY REFERENCES CLIENT(c_id),
	pb_id_branch INT FOREIGN KEY REFERENCES BRANCH(b_id)
);